
executor: "KubernetesExecutor"  # or "CeleryExecutor", "LocalExecutor", etc.

dags:
  gitSync:
    enabled: false
  persistence:
    enabled: true
    existingClaim: dags-pvc

statsd:
  enabled: false

env:
  - name: AIRFLOW__CORE__LOAD_EXAMPLES
    value: "True"
  - name: AIRFLOW__CORE__LOGGING_LEVEL
    value: "INFO"
  - name: AIRFLOW__WEBSERVER__SHOW_TRIGGER_FORM_IF_NO_PARAMS
    value: "True"
  - name: AIRFLOW_VAR_ENVIRONMENT
    value: "local"

workers:
  persistence:
    # enabled: true
    size: 1Gi

triggerer:
  persistence:
    # enabled: true
    size: 1Gi

primaryHost:
  persistence:
    # enabled: true
    size: 1Gi

# users:
#   - username: "admin"
#     password: "admin"
#     role: "Admin"
#     email: "admin@example.com"
#   - username: "user1"
#     password: "user@123"
#     role: "User"
#     email: "user1@example.com"
#   - username: "user2"
#     password: "user@123"
#     role: "User"
#     email: "user2@example.com"
