
executor: "LocalExecutor"  # or "CeleryExecutor", "LocalExecutor", "KubernetesExecutor" etc.

dags:
  gitSync:
    enabled: false
  persistence:
    enabled: true
    existingClaim: dags-pvc

statsd:
  enabled: true

env:
  - name: AIRFLOW__CORE__LOAD_EXAMPLES
    value: "False"
  - name: AIRFLOW__CORE__LOGGING_LEVEL
    value: "INFO"
  - name: AIRFLOW__WEBSERVER__SHOW_TRIGGER_FORM_IF_NO_PARAMS
    value: "True"
  - name: AIRFLOW_VAR_ENVIRONMENT
    value: "local"
  - name: AIRFLOW__KUBERNETES__XCOM_SIDECAR_IMAGE
    value: "alpine:3.19"

# workers:
#   # Ensures the XCom sidecar image (alpine) can be pulled
#   extraEnv:
#     - name: AIRFLOW__KUBERNETES__XCOM_SIDECAR_IMAGE
#       value: "alpine:3.19"

# kubernetes:
#   # Namespace where KubernetesJobOperator will create Jobs
#   namespace: "airflow"
#   # XCom sidecar container image
#   airflow_xcom_sidecar_image: "alpine:3.19"
#   airflow_xcom_sidecar_resources:
#     requests:
#       memory: "64Mi"
#       cpu: "50m"
#     limits:
#       memory: "128Mi"
#       cpu: "100m"

#   worker_pods_creation_batch_size: 10
#   delete_worker_pods: true
#   delete_worker_pods_on_failure: false

workers:
  persistence:
    # enabled: true
    size: 1Gi
  # extraEnv:
  #   - name: AIRFLOW__KUBERNETES__XCOM_SIDECAR_IMAGE
  #     value: "alpine:3.19"

statsd:
  enabled: false

triggerer:
  persistence:
    # enabled: true
    size: 1Gi

primaryHost:
  persistence:
    # enabled: true
    size: 1Gi

# users:
#   - username: "admin"
#     password: "admin"
#     role: "Admin"
#     email: "admin@example.com"
#   - username: "user1"
#     password: "user@123"
#     role: "User"
#     email: "user1@example.com"
#   - username: "user2"
#     password: "user@123"
#     role: "User"
#     email: "user2@example.com"
