rootUser: "minioadmin"
rootPassword: "min!0@Dmin"

mode: standalone

persistence:
  enabled: true
  size: 10Gi
  storageClass: "standard"  # Change this based on your Kubernetes setup

resources:
  requests:
    memory: 512Mi
    cpu: 250m
  limits:
    memory: 1Gi
    cpu: 500m

service:
  type: ClusterIP
  port: 9000
  consolePort: 9001

buckets:
  - name: local-bucket
    policy: none
    purge: false

users:
  - accessKey: "user1"
    secretKey: "user@123"
    policy: "readwrite"
  - accessKey: "user2"
    secretKey: "user@123"
    policy: "readonly"